### ISSUE TITLE
Using sh with nq-agent returns a syntax error

### ISSUE THREAD

**Issue by manvari** [nodequery/nq-agent#1]
```
root@vps:/etc/nodequery# ./nq-agent.sh
./nq-agent.sh: 26: ./nq-agent.sh: Syntax error: "(" unexpected (expecting "fi")
```

I'm not sure this is a sh script either. Switching to `#!/bin/bash` gets the script working again.

**Comment by nodequery** [comment]
Which distribution are you using? Until now there have been no reports about syntax errors.

**Comment by manvari** [comment]
I'm using Debian Wheezy (7.4). Strangely, this only happens on my OpenVZ VPS, whilst my KVM one has no issue running the script.

**Comment by nodequery** [comment]
Thank you, I will look into it as soon as I have a moment to spare.

**Comment by nodequery** [comment]
Changed to <code>#!/bin/bash</code> in upcoming version.
