### ISSUE TITLE
--no-check-certificate missing from wget install

### ISSUE THREAD

**Issue by hyperknot** [nodequery/nq-agent#3]
The wget install command offered on the website should contain `--no-check-certificate`, as this is needed on most minimal server installs.

**Comment by elijahpaul** [comment]
Yep. wget versions 1.12-4.fc14 on CentOS/RHEL and 1.10.2-2 on Debian are buggy and fail to check Subject Alternative Names (SAN) properly.

Upgrading wget will correct this problem and eliminate the errors.

[RedHat Bug Report](https://bugzilla.redhat.com/show_bug.cgi?id=674186) / [Debian Bug Report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=409938) concerning wget and certificate SANs

**Comment by hyperknot** [comment]
No, a brand new Debian Wheezy netinstall will produce the same error,
because certificates are not installed by default.
And no, I don't believe the right solution is to install a package just to
wget a small file

**Comment by nodequery** [comment]
Users tend to mistrust SSL requests that do not check the certificate. However, considering how many distributions do not ship with the required package, we will most likely add the parameter with the next web application update.

**Comment by nodequery** [comment]
We've added the parameter to the installation routine until we come up with a better solution.
